# Generated by Django 2.2.5 on 2019-10-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='Profile_Pics/default.jpg', upload_to='Profile_Pics'),
        ),
    ]
